### ISSUE TITLE
No devices or entities

### ISSUE THREAD

**Issue by mtweets** [tijsverkoyen/HomeAssistant-FusionSolar#239]
Fusion Solar stopped working. I guessed the URL wasn't valid anymore after being used more than a year. So I removed and then reinstalled Fusion Solar. I took the new (?) Kiosk URL. But the hub mentions 'No devices or entities'.

![Image](https://github.com/user-attachments/assets/dcb2c70f-af57-4f3a-a1ef-11ff37c675a7)

I got the Kiosk URL from logging in to uni001eu5.fusionsolar.huawei.com.  If I copy that URL in the same session, in a new tab, it show me all available information. But when I open that url in another session with my browser, it shows a 'The resource does not exist.' That's probably the reason that HomeAssistant shows 'No devices or entities'?

Some info from the log [home-assistant_2025-04-12T18-10-41.645Z.log](https://github.com/user-attachments/files/19730934/home-assistant_2025-04-12T18-10-41.645Z.log):
`2025-04-12 19:06:12.914 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration fusion_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-12 19:08:19.271 WARNING (ImportExecutor_0) [homeassistant.core] Config was used from fusion_solar, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'fusion_solar' custom integration
2025-04-12 19:08:34.058 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'fusion_solar' calls async_forward_entry_setup for integration, fusion_solar with title: Fusion Solar and entry_id: 01JRNFJXM15G6PQAVVBFVET7QY, which is deprecated, await async_forward_entry_setups instead at custom_components/fusion_solar/__init__.py, line 23: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please create a bug report at https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues
2025-04-12 19:08:34.094 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.fusion_solar.sensor',) in /usr/src/homeassistant/homeassistant/loader.py, line 1281: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
(...)
  File "/config/custom_components/fusion_solar/sensor.py", line 32, in <module>
    from .fusion_solar.year_plant_data_entity import *
  File "/config/custom_components/fusion_solar/fusion_solar/year_plant_data_entity.py", line 5, in <module>
    from homeassistant.const import UnitOfEnergy, UnitOfPower, UnitOfMass, IRRADIATION_WATTS_PER_SQUARE_METER
ImportError: cannot import name 'IRRADIATION_WATTS_PER_SQUARE_METER' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`

**Comment by tijsverkoyen** [comment]
You have version 3.0.0. While the latest version is 3.3.0. Please update to the latest version of the integration.

**Comment by mtweets** [comment]
Hello @tijsverkoyen, thanks for your response! I installed it by using the steps at https://github.com/tijsverkoyen/HomeAssistant-FusionSolar?tab=readme-ov-file#installation, namely "you need to add it in Home Assistant: Settings → Devices & Services → Add Integration → Search for FusionSolar.". That gave me FusionSolar version 3.0.0 on Home Assistant Container  (Core 2025.4.2 and Frontend 20250411.0). Any ideas how I can upgrade to 3.3.0?

**Comment by tijsverkoyen** [comment]
I don't know how you have HACS installed. But when I open HACS and search for Fusion Solar and click the repo I see the 3.3.0 version.

![Image](https://github.com/user-attachments/assets/6094b24c-3d55-4b94-855e-c92bf66aba25)

**Comment by mtweets** [comment]
Hello Tijs, thanks for your feedback.

When I wrote "Home Assistant Container", I meant the installation method from https://www.home-assistant.io/installation/linux#install-home-assistant-container. Within that docker image, I didn't install HACS. I just went to http://IP:8123/config/integrations/dashboard > Add Integration > Search for FusionSolar > etc... But that gives me version 3.0.0 instead of the latest version. Would thát version be updated eventually?

I now also [installed HACS](https://www.hacs.xyz/docs/use/) to have the latest version of FusionSolar. I was a bit surprised I needed to logon to GitHub within HACS, but anyway: I have FusionSolar 3.3.0 now.

And about my:
> I got the Kiosk URL from logging in to uni001eu5.fusionsolar.huawei.com. If I copy that URL in the same session, in a new tab, it show me all available information. But when I open that url in another session with my browser, it shows a 'The resource does not exist.' That's probably the reason that HomeAssistant shows 'No devices or entities'?

I must have made an error in copy-pasting by accidentally adding a letter to the url 🤦‍♂️. 

I now tested both the Kiosk and OpenAPI ways and both of them seem to be working on my own HA 👍. As I understand the OpenAPI is preferred as this one is more frequently updated. I now only have to try it out on my parents their system.

Thanks for the quick help!

**Comment by tijsverkoyen** [comment]
> When I wrote "Home Assistant Container", I meant the installation method from https://www.home-assistant.io/installation/linux#install-home-assistant-container. Within that docker image, I didn't install HACS. I just went to http://ip:8123/config/integrations/dashboard > Add Integration > Search for FusionSolar > etc... But that gives me version 3.0.0 instead of the latest version. Would thát version be updated eventually?

I don't know. I don't know how they fetch releases. I think you should open een issue on Home Assistant.

> now also [installed HACS](https://www.hacs.xyz/docs/use/) to have the latest version of FusionSolar. I was a bit surprised I needed to logon to GitHub within HACS, but anyway: I have FusionSolar 3.3.0 now.

I don't know the internals of HACS. But I suspect it is to prevent rate limiting.

> I now tested both the Kiosk and OpenAPI ways and both of them seem to be working on my own HA 👍. As I understand the OpenAPI is preferred as this one is more frequently updated. I now only have to try it out on my parents their system.

Both have delay. Kiosk has about 15min delay. OpenAPI depends on the number of devices. You can disable devices you don't need. See https://github.com/tijsverkoyen/HomeAssistant-FusionSolar?tab=readme-ov-file#disabling-devices--plants--stations
